name: Test

on:
  pull_request:
    paths-ignore:
      - '*.md'
      - '*.asciidoc'

jobs:
  gradle:
    strategy:
      matrix:
        os: [ubuntu-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout the repo
        uses: actions/checkout@v1
      - name: Validate Gradle Wrapper
        uses: gradle/wrapper-validation-action@v1
      - name: Cache gradle
        uses: actions/cache@v1
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
      - name: Setup java
        uses: actions/setup-java@v1
        with:
          java-version: 8
      - name: Export PR_NUMBER
        run: |
          echo ::set-env name=PR_NUMBER::$(echo "$GITHUB_REF" | awk -F / '{print $3}')
      - name: Execute tests
        id: gradle
        uses: eskatos/gradle-command-action@v1
        with:
          arguments: :check
      - name: Comment on PR with build scan
        uses: mshick/add-pr-comment@v1
        if: failure()
        with:
          repo-token: ${{ secrets.githubToken }}
          message: Build failed ${{ steps.gradle.outputs.build-scan-url }}
      - name: Store hprof files
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: hprofs
          path: ./**/*.hprof